-- HireIn AI production schema. Safe to re-run in the Supabase SQL editor.
-- Existing jobs/applications tables are extended in place.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text,
  role text not null default 'candidate' check (role in ('candidate', 'recruiter', 'admin')),
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
update public.profiles p set email = u.email from auth.users u where p.user_id = u.id and p.email is distinct from u.email;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  slug text unique,
  logo_url text,
  website text,
  location text,
  description text not null default '',
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null default '',
  company_id uuid references public.companies(id) on delete set null,
  location text not null default '',
  employment_type text not null default 'Full time',
  type text,
  work_mode text not null default 'Onsite' check (work_mode in ('Remote', 'Hybrid', 'Onsite')),
  experience text not null default '',
  salary text not null default '',
  salary_min numeric,
  salary_max numeric,
  currency text not null default 'INR',
  description text not null default '',
  responsibilities text not null default '',
  requirements text not null default '',
  skills text[] not null default '{}',
  benefits text not null default '',
  category text not null default '',
  logo text,
  ai_match integer,
  status text not null default 'draft' check (status in ('draft', 'published', 'active', 'paused', 'closed', 'rejected')),
  featured boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  posted_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.jobs add column if not exists company_id uuid references public.companies(id) on delete set null;
alter table public.jobs add column if not exists employment_type text not null default 'Full time';
alter table public.jobs add column if not exists type text;
alter table public.jobs add column if not exists work_mode text not null default 'Onsite';
alter table public.jobs add column if not exists experience text not null default '';
alter table public.jobs add column if not exists salary_min numeric;
alter table public.jobs add column if not exists salary_max numeric;
alter table public.jobs add column if not exists currency text not null default 'INR';
alter table public.jobs add column if not exists responsibilities text not null default '';
alter table public.jobs add column if not exists requirements text not null default '';
alter table public.jobs add column if not exists skills text[] not null default '{}';
alter table public.jobs add column if not exists benefits text not null default '';
alter table public.jobs add column if not exists featured boolean not null default false;
alter table public.jobs add column if not exists expires_at timestamptz;
alter table public.jobs add column if not exists updated_at timestamptz not null default now();
alter table public.jobs add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.jobs add column if not exists status text not null default 'published';

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  name text not null default '',
  email text not null default '',
  phone text not null default '',
  portfolio text,
  cover_letter text,
  resume_url text,
  resume_path text,
  status text not null default 'Applied' check (status in ('Applied', 'Reviewing', 'Shortlisted', 'Interview', 'Rejected', 'Hired')),
  applied_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, user_id)
);

alter table public.applications add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.applications add column if not exists name text not null default '';
alter table public.applications add column if not exists email text not null default '';
alter table public.applications add column if not exists phone text not null default '';
alter table public.applications add column if not exists portfolio text;
alter table public.applications add column if not exists cover_letter text;
alter table public.applications add column if not exists resume_url text;
alter table public.applications add column if not exists resume_path text;
alter table public.applications add column if not exists applied_at timestamptz not null default now();
alter table public.applications add column if not exists updated_at timestamptz not null default now();
alter table public.applications alter column status set default 'Applied';

create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create table if not exists public.resumes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  storage_path text not null unique,
  pdf_url text,
  template text not null default 'modern' check (template in ('modern', 'minimal', 'executive', 'creative')),
  resume_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.resumes add column if not exists pdf_url text;
alter table public.resumes add column if not exists template text not null default 'modern';
alter table public.resumes add column if not exists resume_data jsonb not null default '{}'::jsonb;
alter table public.resumes add column if not exists updated_at timestamptz not null default now();

create table if not exists public.ats_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id bigint references public.jobs(id) on delete set null,
  resume_name text not null,
  resume_path text,
  score integer not null check (score between 0 and 100),
  matched_keywords text[] not null default '{}',
  missing_keywords text[] not null default '{}',
  suggestions text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.ats_history add column if not exists resume_path text;
alter table public.ats_history add column if not exists details jsonb not null default '{}'::jsonb;

create table if not exists public.job_views (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  viewer_id uuid references auth.users(id) on delete set null,
  session_id text,
  viewed_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null default '',
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  person_name text not null,
  role text not null default '',
  company_name text not null default '',
  quote text not null,
  is_approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists jobs_public_sort_idx on public.jobs(status, posted_at desc, id desc);
create index if not exists jobs_owner_idx on public.jobs(created_by, created_at desc);
create index if not exists jobs_company_idx on public.jobs(company_id);
create index if not exists applications_user_idx on public.applications(user_id, applied_at desc);
create index if not exists applications_job_idx on public.applications(job_id, applied_at desc);
create index if not exists saved_jobs_user_idx on public.saved_jobs(user_id, created_at desc);
create index if not exists ats_history_user_idx on public.ats_history(user_id, created_at desc);
create index if not exists resumes_user_idx on public.resumes(user_id, created_at desc);
create index if not exists job_views_job_idx on public.job_views(job_id, viewed_at desc);
create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);

create or replace function public.hirein_has_role(roles text[])
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where user_id = auth.uid() and role = any(roles)); $$;
revoke all on function public.hirein_has_role(text[]) from public;
grant execute on function public.hirein_has_role(text[]) to authenticated;

create or replace function public.handle_new_hirein_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles(user_id, full_name, email, role)
  values(new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), new.email, 'candidate')
  on conflict (user_id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_hirein_auth_user_created on auth.users;
create trigger on_hirein_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_hirein_user();

create or replace function public.sync_hirein_profile_email()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  update public.profiles set email = new.email where user_id = new.id;
  return new;
end;
$$;
drop trigger if exists on_hirein_auth_email_changed on auth.users;
create trigger on_hirein_auth_email_changed after update of email on auth.users
for each row when (old.email is distinct from new.email)
execute procedure public.sync_hirein_profile_email();

create or replace function public.prevent_self_role_change()
returns trigger language plpgsql set search_path = public
as $$
begin
  if auth.uid() is not null and new.role is distinct from old.role
     and not public.hirein_has_role(array['admin']) then
    raise exception 'Only an administrator can change account roles';
  end if;
  if auth.uid() is not null and new.email is distinct from old.email
     and not public.hirein_has_role(array['admin']) then
    raise exception 'Account email must be changed through authentication settings';
  end if;
  new.updated_at := now();
  return new;
end;
$$;
drop trigger if exists prevent_hirein_role_change on public.profiles;
create trigger prevent_hirein_role_change before update on public.profiles
for each row execute procedure public.prevent_self_role_change();

create or replace function public.hirein_touch_updated_at()
returns trigger language plpgsql set search_path = public
as $$ begin new.updated_at := now(); return new; end; $$;
drop trigger if exists hirein_jobs_touch_updated_at on public.jobs;
create trigger hirein_jobs_touch_updated_at before update on public.jobs for each row execute procedure public.hirein_touch_updated_at();
drop trigger if exists hirein_companies_touch_updated_at on public.companies;
create trigger hirein_companies_touch_updated_at before update on public.companies for each row execute procedure public.hirein_touch_updated_at();
drop trigger if exists hirein_applications_touch_updated_at on public.applications;
create trigger hirein_applications_touch_updated_at before update on public.applications for each row execute procedure public.hirein_touch_updated_at();
drop trigger if exists hirein_resumes_touch_updated_at on public.resumes;
create trigger hirein_resumes_touch_updated_at before update on public.resumes for each row execute procedure public.hirein_touch_updated_at();

alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.jobs enable row level security;
alter table public.applications enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.resumes enable row level security;
alter table public.ats_history enable row level security;
alter table public.job_views enable row level security;
alter table public.notifications enable row level security;
alter table public.testimonials enable row level security;

drop policy if exists "Allow public application submissions" on public.applications;
drop policy if exists hirein_profiles_read_self on public.profiles;
create policy hirein_profiles_read_self on public.profiles for select to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_profiles_update_self on public.profiles;
create policy hirein_profiles_update_self on public.profiles for update to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']))
with check (user_id = auth.uid() or public.hirein_has_role(array['admin']));

drop policy if exists hirein_companies_public_read on public.companies;
create policy hirein_companies_public_read on public.companies for select to anon, authenticated
using (is_approved or owner_id = auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_companies_owner_manage on public.companies;
create policy hirein_companies_owner_manage on public.companies for all to authenticated
using (owner_id = auth.uid() or public.hirein_has_role(array['admin']))
with check ((owner_id = auth.uid() and public.hirein_has_role(array['recruiter', 'admin'])) or public.hirein_has_role(array['admin']));

drop policy if exists hirein_jobs_public_read on public.jobs;
create policy hirein_jobs_public_read on public.jobs for select to anon, authenticated
using (status in ('published', 'active') and (expires_at is null or expires_at > now()));
drop policy if exists hirein_jobs_owner_read on public.jobs;
create policy hirein_jobs_owner_read on public.jobs for select to authenticated
using (created_by = auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_jobs_recruiter_insert on public.jobs;
create policy hirein_jobs_recruiter_insert on public.jobs for insert to authenticated
with check (created_by = auth.uid() and public.hirein_has_role(array['recruiter', 'admin']));
drop policy if exists hirein_jobs_recruiter_update on public.jobs;
create policy hirein_jobs_recruiter_update on public.jobs for update to authenticated
using (public.hirein_has_role(array['admin']) or (created_by = auth.uid() and public.hirein_has_role(array['recruiter'])))
with check (public.hirein_has_role(array['admin']) or (created_by = auth.uid() and public.hirein_has_role(array['recruiter'])));
drop policy if exists hirein_jobs_recruiter_delete on public.jobs;
create policy hirein_jobs_recruiter_delete on public.jobs for delete to authenticated
using (public.hirein_has_role(array['admin']) or (created_by = auth.uid() and public.hirein_has_role(array['recruiter'])));

drop policy if exists hirein_apps_candidate_insert on public.applications;
create policy hirein_apps_candidate_insert on public.applications for insert to authenticated
with check (user_id = auth.uid() and
  (resume_path is null or split_part(resume_path, '/', 1) = auth.uid()::text) and
  (resume_url is null or (resume_path is null and split_part(resume_url, '/', 1) = auth.uid()::text) or resume_url = resume_path));
drop policy if exists hirein_apps_candidate_read on public.applications;
create policy hirein_apps_candidate_read on public.applications for select to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']) or
  (public.hirein_has_role(array['recruiter']) and exists
    (select 1 from public.jobs j where j.id = applications.job_id and j.created_by = auth.uid())));
drop policy if exists hirein_apps_recruiter_update on public.applications;
create policy hirein_apps_recruiter_update on public.applications for update to authenticated
using (public.hirein_has_role(array['admin']) or (public.hirein_has_role(array['recruiter']) and exists
  (select 1 from public.jobs j where j.id = applications.job_id and j.created_by = auth.uid())))
with check (public.hirein_has_role(array['admin']) or (public.hirein_has_role(array['recruiter']) and exists
  (select 1 from public.jobs j where j.id = applications.job_id and j.created_by = auth.uid())));
drop policy if exists hirein_apps_admin_delete on public.applications;
create policy hirein_apps_admin_delete on public.applications for delete to authenticated
using (public.hirein_has_role(array['admin']));

drop policy if exists hirein_saved_jobs_owner_all on public.saved_jobs;
create policy hirein_saved_jobs_owner_all on public.saved_jobs for all to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']))
with check (user_id = auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_ats_owner_select on public.ats_history;
create policy hirein_ats_owner_select on public.ats_history for select to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_ats_owner_insert on public.ats_history;
create policy hirein_ats_owner_insert on public.ats_history for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists hirein_ats_owner_delete on public.ats_history;
create policy hirein_ats_owner_delete on public.ats_history for delete to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']));
drop policy if exists hirein_resumes_owner_all on public.resumes;
create policy hirein_resumes_owner_all on public.resumes for all to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']))
with check (user_id = auth.uid() or public.hirein_has_role(array['admin']));

drop policy if exists hirein_job_views_public_insert on public.job_views;
create policy hirein_job_views_public_insert on public.job_views for insert to anon, authenticated
with check ((viewer_id is null or viewer_id = auth.uid()) and exists (select 1 from public.jobs j where j.id = job_views.job_id and j.status in ('published', 'active')));
drop policy if exists hirein_job_views_owner_read on public.job_views;
create policy hirein_job_views_owner_read on public.job_views for select to authenticated
using (public.hirein_has_role(array['admin']) or exists
  (select 1 from public.jobs j where j.id = job_views.job_id and j.created_by = auth.uid()));
drop policy if exists hirein_notifications_owner_all on public.notifications;
create policy hirein_notifications_owner_all on public.notifications for all to authenticated
using (user_id = auth.uid() or public.hirein_has_role(array['admin']))
with check (user_id = auth.uid() or public.hirein_has_role(array['admin']));

drop policy if exists hirein_testimonials_public_read on public.testimonials;
create policy hirein_testimonials_public_read on public.testimonials for select to anon, authenticated
using (is_approved or public.hirein_has_role(array['admin']));
drop policy if exists hirein_testimonials_admin_manage on public.testimonials;
create policy hirein_testimonials_admin_manage on public.testimonials for all to authenticated
using (public.hirein_has_role(array['admin'])) with check (public.hirein_has_role(array['admin']));

grant select on public.jobs, public.companies to anon, authenticated;
grant insert, update, delete on public.jobs to authenticated;
grant select, insert, update, delete on public.applications to authenticated;
grant select, insert, delete on public.saved_jobs to authenticated;
grant select, insert, update, delete on public.resumes to authenticated;
grant select, insert, delete on public.ats_history to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.companies to authenticated;
grant select, insert on public.job_views to anon, authenticated;
grant select, insert, update, delete on public.notifications to authenticated;
grant select, insert, update, delete on public.testimonials to authenticated;
grant select on public.testimonials to anon;

insert into storage.buckets(id, name, public) values ('resumes', 'resumes', false)
on conflict (id) do update set public = false;
insert into storage.buckets(id, name, public) values ('logos', 'logos', true)
on conflict (id) do update set public = true;
insert into storage.buckets(id, name, public) values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists hirein_resume_owner_upload on storage.objects;
create policy hirein_resume_owner_upload on storage.objects for insert to authenticated
with check (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists hirein_resume_owner_read on storage.objects;
create policy hirein_resume_owner_read on storage.objects for select to authenticated
using (bucket_id = 'resumes' and ((storage.foldername(name))[1] = auth.uid()::text or public.hirein_has_role(array['admin']) or
  (public.hirein_has_role(array['recruiter']) and exists
    (select 1 from public.applications a join public.jobs j on j.id = a.job_id
     where coalesce(a.resume_path, a.resume_url) = name and j.created_by = auth.uid()))));
drop policy if exists hirein_resume_owner_delete on storage.objects;
create policy hirein_resume_owner_delete on storage.objects for delete to authenticated
using (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists hirein_public_brand_asset_read on storage.objects;
create policy hirein_public_brand_asset_read on storage.objects for select to anon, authenticated
using (bucket_id in ('logos', 'avatars'));
drop policy if exists hirein_brand_asset_owner_upload on storage.objects;
create policy hirein_brand_asset_owner_upload on storage.objects for insert to authenticated
with check (bucket_id in ('logos', 'avatars') and (storage.foldername(name))[1] = auth.uid()::text
  and public.hirein_has_role(array['recruiter', 'admin']));
drop policy if exists hirein_brand_asset_owner_update on storage.objects;
create policy hirein_brand_asset_owner_update on storage.objects for update to authenticated
using (bucket_id in ('logos', 'avatars') and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id in ('logos', 'avatars') and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists hirein_brand_asset_owner_delete on storage.objects;
create policy hirein_brand_asset_owner_delete on storage.objects for delete to authenticated
using (bucket_id in ('logos', 'avatars') and (storage.foldername(name))[1] = auth.uid()::text);

-- Promote recruiters only from the Supabase SQL editor after verifying the account:
-- update public.profiles p set role = 'recruiter' from auth.users u
-- where p.user_id = u.id and u.email = 'recruiter@example.com';
